version: '3' # 目前使用的版本
services:
    # services 關鍵字後面列出 web, redis 兩項專案中的服務
    php:
        image: cc711612/php8.1-fpm-alpine:1.3
        restart: always
        container_name: ${PROJECT_NAME}-php-fpm
        links:
            - "redis"
        environment:
            - TZ=Asia/Taipei
        volumes:
            - ${PROJECT_PATH}:/var/www/html
            - ./entrypoint.sh:/entrypoint.sh
            - ./main_crontabs/schedule:/etc/crontabs/schedule # alpine crontab 使用
            - ./main_crontabs/root:/etc/crontabs/root # alpine crontab 使用
            - ./supervisor/supervisor.d:/etc/supervisor.d
            - ./supervisor/supervisord.conf:/etc/supervisord.conf
        command: /bin/sh -c "/entrypoint.sh"
        dns:
            - 8.8.8.8
    nginx:
        image: nginx
        restart: always
        container_name: ${PROJECT_NAME}-nginx
        ports:
            - "${NGINX_HTTP_PORT}:80"
            - "${NGINX_HTTPS_PORT}:443"
        links:
            - "php"
        volumes:
            - ${PROJECT_PATH}:/usr/share/nginx/html
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/ssl:/etc/nginx/ssl
    redis:
        image: redis:latest
        restart: always
        container_name: ${PROJECT_NAME}-redis
        environment:
            - TZ=Asia/Taipei