version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../../:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile.php82.cache  # 使用 Cache Mount 版本
    environment:
      - RUN_MODE=${RUN_MODE:-fpm}
    volumes:
      - ../../:/var/www/html
    networks:
      - laravel
    expose:
      - "9000"
      - "8000"

  redis:
    image: redis:alpine
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wallet
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel
    ports:
      - "3306:3306"

networks:
  laravel:
    driver: bridge

volumes:
  mysql_data:
    driver: local
