<?php

/**
 * @Author: Roy
 * @DateTime: 2022/6/21 上午 11:25
 */

namespace App\Models\Users\Databases\Services;

use App\Concerns\Databases\Service;
use Illuminate\Database\Eloquent\Model;
use App\Models\Users\Databases\Entities\UserEntity;
use Illuminate\Support\Facades\Cache;

class UserApiService extends Service
{
    /**
     * @return \Illuminate\Database\Eloquent\Model
     * @Author: Roy
     * @DateTime: 2022/6/21 上午 11:27
     */
    protected function getEntity(): Model
    {
        // TODO: Implement getEntity() method.
        if (app()->has(UserEntity::class) === false) {
            app()->singleton(UserEntity::class);
        }

        return app(UserEntity::class);
    }

    /**
     * @param  array  $create
     *
     * @return \Illuminate\Database\Eloquent\Model
     * @Author: Roy
     * @DateTime: 2022/6/21 上午 11:27
     */
    public function create(array $create): Model
    {
        return parent::create($create); // TODO: Change the autogenerated stub
    }

    public function find($id)
    {
        $cacheKey = 'user.' . $id;
        if (Cache::get($cacheKey)) {
            return Cache::get($cacheKey);
        }
        $user = $this->getEntity()->with(['wallet_users'])->find($id);
        if ($user) {
            Cache::put($cacheKey, $user, 3600);
        }

        return $user;
    }
}
