name: Deploy

# 觸發條件：針對 push 和 pull request 事件
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # 根據分支設置環境變數
      - name: Set environment based on branch
        id: set-env
        run: |
          if [ "${{ github.ref }}" == "refs/heads/master" ]; then
            echo "ENVIRONMENT=production" >> $GITHUB_ENV
            echo "DEPLOY_HOST=${{ secrets.PRODUCTION_HOST }}" >> $GITHUB_ENV
            echo "DEPLOY_USERNAME=${{ secrets.PRODUCTION_USERNAME }}" >> $GITHUB_ENV
            echo "DEPLOY_PORT=${{ secrets.PRODUCTION_PORT }}" >> $GITHUB_ENV
            echo "DEPLOY_PATH=${{ secrets.PRODUCTION_PATH }}" >> $GITHUB_ENV
            echo "DEPLOY_SH=${{ secrets.PRODUCTION_SH_PATH }}" >> $GITHUB_ENV
            echo "DEPLOY_SSHKEY<<EOF" >> $GITHUB_ENV
            echo "${{ secrets.PRODUCTION_SSHKEY }}" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          elif [ "${{ github.ref }}" == "refs/heads/develop" ]; then
            echo "ENVIRONMENT=development" >> $GITHUB_ENV
            echo "DEPLOY_HOST=${{ secrets.DEVELOP_HOST }}" >> $GITHUB_ENV
            echo "DEPLOY_USERNAME=${{ secrets.DEVELOP_USERNAME }}" >> $GITHUB_ENV
            echo "DEPLOY_PORT=${{ secrets.DEVELOP_PORT }}" >> $GITHUB_ENV
            echo "DEPLOY_PATH=${{ secrets.DEVELOP_PATH }}" >> $GITHUB_ENV
            echo "DEPLOY_SH=${{ secrets.DEVELOP_SH_PATH }}" >> $GITHUB_ENV
            echo "DEPLOY_SSHKEY<<EOF" >> $GITHUB_ENV
            echo "${{ secrets.DEVELOP_SSHKEY }}" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          fi

      # 執行部署
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.DEPLOY_HOST }}
          username: ${{ env.DEPLOY_USERNAME }}
          port: ${{ env.DEPLOY_PORT }}
          key: ${{ env.DEPLOY_SSHKEY }}
          script: |
            set -e
            echo "=== 開始部署到 ${{ env.ENVIRONMENT }} 環境 ==="
            echo "當前使用者: $(whoami)"
            echo "當前目錄: $(pwd)"
            echo "部署路徑: ${{ env.DEPLOY_PATH }}"
            echo "部署腳本: ${{ env.DEPLOY_SH }}"
            
            # 檢查部署路徑是否存在
            if [ ! -d "${{ env.DEPLOY_PATH }}" ]; then
              echo "錯誤: 部署路徑不存在: ${{ env.DEPLOY_PATH }}"
              exit 1
            fi
            
            # 進入部署目錄
            cd ${{ env.DEPLOY_PATH }}
            echo "已進入部署目錄: $(pwd)"
            
            # 檢查部署腳本是否存在
            if [ ! -f "${{ env.DEPLOY_SH }}" ]; then
              echo "錯誤: 部署腳本不存在: ${{ env.DEPLOY_SH }}"
              exit 1
            fi
            
            # 設定執行權限
            echo "設定腳本執行權限..."
            chmod +x "${{ env.DEPLOY_SH }}"
            
            # 執行部署腳本
            echo "執行部署腳本..."
            bash "${{ env.DEPLOY_SH }}"
            
            echo "=== 部署完成 ==="